// Regenerates src/svg/font-data.ts: woff2 subsets embedded as data URIs.
// Requires `uvx` (fonttools + brotli are fetched on demand) and the local Latin Modern / Noto CJK fonts.
// Latin faces get a fixed ASCII + punctuation + Greek repertoire; the CJK face is subset to every
// non-Latin character found in src/svg/**/*.ts and public/**/*.svg, so re-running is idempotent.
import { spawnSync } from 'node:child_process';
import { mkdtempSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { tmpdir, homedir } from 'node:os';
import { join } from 'node:path';

const FONT_DIR = process.env.FONT_SOURCE_DIR ?? join(homedir(), '.local/share/fonts');
const LATIN_RANGE = 'U+0020-007E,U+00A0-00FF,U+0100-017F,U+2013,U+2014,U+2018,U+2019,U+201C,U+201D,U+2020,U+2021,U+2022,U+2026,U+2030,U+2032,U+2033,U+2044,U+20AC,U+2116,U+2122,U+2190-2199,U+21BA,U+21BB,U+2202,U+2206,U+220F,U+2211,U+2212,U+221A,U+221E,U+2248,U+2260,U+2264,U+2265,U+25A0-25CF,U+0391-03A9,U+03B1-03C9,U+2070-209F,U+00B2,U+00B3,U+00B9,U+2153-215E,U+00BC-00BE';
const faces = [
  { family: 'Studio Serif', weight: 400, style: 'normal', file: 'latinmodern/lmroman10-regular.otf', unicodes: LATIN_RANGE },
  { family: 'Studio Serif', weight: 700, style: 'normal', file: 'latinmodern/lmroman10-bold.otf', unicodes: LATIN_RANGE },
  { family: 'Studio Serif', weight: 400, style: 'italic', file: 'latinmodern/lmroman10-italic.otf', unicodes: LATIN_RANGE },
  { family: 'Studio Mono', weight: 400, style: 'normal', file: 'latinmodern/lmmono10-regular.otf', unicodes: LATIN_RANGE },
  { family: 'Studio Sans', weight: 400, style: 'normal', file: 'noto-cjk/NotoSansCJK-Regular.ttc', fontNumber: 3, unicodes: LATIN_RANGE },
  { family: 'Studio Sans', weight: 700, style: 'normal', file: 'noto-cjk/NotoSansCJK-Bold.ttc', fontNumber: 3, unicodes: LATIN_RANGE },
];

const walk = (dir, out = []) => { for (const name of readdirSync(dir)) { const p = join(dir, name); statSync(p).isDirectory() ? walk(p, out) : out.push(p); } return out; };
const sources = [...walk('src/svg'), ...walk('public')].filter(p => /\.(ts|svg|html|json)$/.test(p) && !p.endsWith('font-data.ts'));
const cjk = new Set();
for (const file of sources) for (const ch of readFileSync(file, 'utf8')) { const cp = ch.codePointAt(0); if (cp >= 0x2E80 && cp <= 0xFFEF) cjk.add(cp); }
const cjkList = [...cjk].sort((a, b) => a - b);
if (cjkList.length) {
  const unicodes = cjkList.map(cp => 'U+' + cp.toString(16).toUpperCase().padStart(4, '0')).join(',');
  faces.push({ family: 'Studio CJK', weight: 400, style: 'normal', file: 'noto-cjk/NotoSansCJK-Regular.ttc', fontNumber: 3, unicodes });
  faces.push({ family: 'Studio CJK', weight: 700, style: 'normal', file: 'noto-cjk/NotoSansCJK-Bold.ttc', fontNumber: 3, unicodes });
}

const tmp = mkdtempSync(join(tmpdir(), 'studio-fonts-'));
const out = [];
for (const [i, face] of faces.entries()) {
  const target = join(tmp, `${i}.woff2`);
  const args = ['--from', 'fonttools', '--with', 'brotli', 'pyftsubset', join(FONT_DIR, face.file), `--unicodes=${face.unicodes}`, '--flavor=woff2', `--output-file=${target}`, '--layout-features=*', '--no-hinting', '--desubroutinize'];
  if (face.fontNumber !== undefined) args.push(`--font-number=${face.fontNumber}`);
  const result = spawnSync('uvx', args, { stdio: ['ignore', 'pipe', 'pipe'] });
  if (result.status !== 0) throw new Error(`pyftsubset failed for ${face.file}: ${result.stderr}`);
  const data = readFileSync(target).toString('base64');
  out.push({ family: face.family, weight: face.weight, style: face.style, dataUri: `data:font/woff2;base64,${data}` });
  console.log(`${face.family} ${face.weight} ${face.style}: ${(data.length * 3 / 4 / 1024).toFixed(1)} KB`);
}
const header = `// GENERATED by scripts/build-fonts.mjs — do not edit. Latin Modern (GUST font licence) + Noto Sans CJK (OFL) subsets.\n// CJK repertoire: ${cjkList.length} code points harvested from src/svg and public.\n`;
writeFileSync('src/svg/font-data.ts', `${header}export interface EmbeddedFace { family: string; weight: number; style: string; dataUri: string }\nexport const EMBEDDED_FACES: EmbeddedFace[] = ${JSON.stringify(out, null, 1)};\n`);
console.log(`wrote src/svg/font-data.ts (${faces.length} faces, ${cjkList.length} CJK code points)`);
